### ISSUE TITLE
Your repo bash scripts are not working in Ubuntu 20.04 (e.g. script/Download_HICO-DET.sh)

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#14]
```
[26744:2271 0:477] 01:56:09 Thu Dec 24 [mona@goku:pts/5 +1] ~/research/code/DJ-RN
$ bash  script/Download_HICO-DET.sh
script/Download_data.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:
^CTraceback (most recent call last):
  File "script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "script/Download_data.py", line 25, in save_response_content
    for chunk in response.iter_content(CHUNK_SIZE):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 710, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/mona/anaconda3/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/home/mona/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


```

**Comment by monacv** [comment]
```
[26744:2271 0:479] 01:58:06 Thu Dec 24 [mona@goku:pts/5 +1] ~/research/code/DJ-RN
$ python script/Download_data.py 1QZcJmGVlF9f4h-XLWe9Gkmnmj2z1gSnk Data/hico_20160224_det.tar.gz
script/Download_data.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:
^CTraceback (most recent call last):
  File "script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "script/Download_data.py", line 25, in save_response_content
    for chunk in response.iter_content(CHUNK_SIZE):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 710, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "/home/mona/anaconda3/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/home/mona/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt


```

**Comment by monacv** [comment]
Had to download manually like the following:

https://drive.google.com/file/d/1QZcJmGVlF9f4h-XLWe9Gkmnmj2z1gSnk/view
