### ISSUE TITLE
NaN loss value, stopping! --> File "/home/mona/research/code/smplify-x/smplifyx/fit_single_frame.py", line 366, in fit_single_frame tqdm.write('Camera initialization final loss {:.4f}'.format( TypeError: unsupported format string passed to NoneType.__format__

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#28]
After processing some images successfully, I got this error. Is there a fix for it?
```
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00000469.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 0.7507
Camera initialization final loss 1283.9620
Stage 000 done after 2.0166 seconds                                                                                                
Stage 001 done after 1.8066 seconds                                                                                                
Stage 002 done after 1.7855 seconds                                                                                                
Stage 003 done after 6.2607 seconds                                                                                                
Stage 004 done after 6.4354 seconds                                                                                                
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:18<00:00,  3.66s/it]
Body fitting Orientation 0 done after 18.3112 seconds                                                                              
Body final loss val = 7074.32373                                                                                                   
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:18<00:00, 18.31s/it]
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00000470.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 0.9054
Camera initialization final loss 805.9324
Stage 000 done after 2.0088 seconds                                                                                                
Stage 001 done after 0.6831 seconds                                                                                                
Stage 002 done after 2.9054 seconds                                                                                                
Stage 003 done after 7.4240 seconds                                                                                                
Stage 004 done after 1.3566 seconds                                                                                                
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:14<00:00,  2.88s/it]
Body fitting Orientation 0 done after 14.3841 seconds                                                                              
Body final loss val = 1076.25085                                                                                                   
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:14<00:00, 14.38s/it]
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 0.8964
Camera initialization final loss 10146.6113
Stage 000 done after 2.3258 seconds                                                                                                
Stage 001 done after 1.5916 seconds                                                                                                
Stage 002 done after 3.7246 seconds                                                                                                
Stage 003 done after 13.3136 seconds                                                                                               
Stage 004 done after 3.2600 seconds                                                                                                
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:24<00:00,  4.84s/it]
Body fitting Orientation 0 done after 24.2220 seconds                                                                              
Body final loss val = 196141.98438                                                                                                 
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.22s/it]
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00000471.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
NaN loss value, stopping!
Camera initialization done after 1.2850
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 245, in main
    fit_single_frame(img, keypoints[[person_id]],
  File "/home/mona/research/code/smplify-x/smplifyx/fit_single_frame.py", line 366, in fit_single_frame
    tqdm.write('Camera initialization final loss {:.4f}'.format(
TypeError: unsupported format string passed to NoneType.__format__
```

I am running it as follows:

```
$ cat djrn_fit.sh 
export CUDA_VISIBLE_DEVICES=0
python smplifyx/main.py --config cfg_files/fit_smplx.yaml --data_folder ../../data/smplify-x/djrn_train_data/ --output_folder ../../data/smplify-x/djrn_train_results --visualize="False" --model_folder ../../data/smplify-x/models_smplx_v1_1/models/smplx/SMPLX_NEUTRAL.npz --vposer_ckpt ../../data/smplify-x/vposer_v1_0 --part_segm_fn ../../data/smplify-x/smplx_parts_segm.pkl

python smplifyx/main.py --config cfg_files/fit_smplx.yaml --data_folder ../../data/smplify-x/djrn_test_data/ --output_folder ../../data/smplify-x/djrn_test_results --visualize="False" --model_folder ../../data/smplify-x/models_smplx_v1_1/models/smplx/SMPLX_NEUTRAL.npz --vposer_ckpt ../../data/smplify-x/vposer_v1_0 --part_segm_fn ../../data/smplify-x/smplx_parts_segm.pkl

```

I have:

```
~/research/data/smplify-x/djrn_train_results/meshes
$ numdir
293
~/research/data/smplify-x/djrn_test_results/meshes
$ numdir
338
```

Where numdir is:
`alias numdir='echo `find . -type d | wc -l`-1 | bc'`

**Comment by monacv** [comment]
I also ran it on the server and only for train data and get the same exact error but for a different image:

```
Processing: ../../data/smplify-x/djrn_train_data/images/HICO_train2015_00000419.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 1.7629
Camera initialization final loss 3377.0957
Stage 000 done after 4.0044 seconds
Stage 001 done after 3.5054 seconds
Stage 002 done after 7.3627 seconds
Stage 003 done after 12.8516 seconds
Orientation:   0%|                                                                                           | 0/1 [00:27<?, ?it/sNaN loss value, stopping!███████████████████████████████████████████████████████████▏                 | 4/5 [00:27<00:08,  8.33s/it]
Stage 004 done after 5.7050 seconds
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:33<00:00,  6.69s/it]
Body fitting Orientation 0 done after 33.4430 seconds
Body final loss val = 76030.69531
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:33<00:00, 33.44s/it]
Processing: ../../data/smplify-x/djrn_train_data/images/HICO_train2015_00000420.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
NaN loss value, stopping!
Camera initialization done after 2.5138
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/nfs/dawnlightdb/mona/code/smplify-x-dawnlight/smplifyx/fit_single_frame.py", line 367, in fit_single_frame
    cam_init_loss_val))
TypeError: unsupported format string passed to NoneType.__format__
```
The process has been ongoing on the server for test images and currently is at 

```
data/smplify-x/djrn_test_results/meshes$ numdir
869
```
while
```
data/smplify-x/djrn_train_results/meshes$ numdir
293
```

**Comment by monacv** [comment]
I also ran it on the server and only for train data and get the same exact error but for a different image:

```
Processing: ../../data/smplify-x/djrn_train_data/images/HICO_train2015_00000419.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 1.7629
Camera initialization final loss 3377.0957
Stage 000 done after 4.0044 seconds
Stage 001 done after 3.5054 seconds
Stage 002 done after 7.3627 seconds
Stage 003 done after 12.8516 seconds
Orientation:   0%|                                                                                           | 0/1 [00:27<?, ?it/sNaN loss value, stopping!███████████████████████████████████████████████████████████▏                 | 4/5 [00:27<00:08,  8.33s/it]
Stage 004 done after 5.7050 seconds
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:33<00:00,  6.69s/it]
Body fitting Orientation 0 done after 33.4430 seconds
Body final loss val = 76030.69531
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:33<00:00, 33.44s/it]
Processing: ../../data/smplify-x/djrn_train_data/images/HICO_train2015_00000420.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
NaN loss value, stopping!
Camera initialization done after 2.5138
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "~/code/smplify-x/smplifyx/fit_single_frame.py", line 367, in fit_single_frame
    cam_init_loss_val))
TypeError: unsupported format string passed to NoneType.__format__
```
The process has been ongoing on the server for test images and currently is at 

```
~/data/smplify-x/djrn_test_results/meshes$ numdir
869
```
while
```
~/data/smplify-x/djrn_train_results/meshes$ numdir
293
```

**Comment by monacv** [comment]
also, now, the test images from HICO broke for this image:

```
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00001356.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 1.6837
Camera initialization final loss 4819.7524
Stage 000 done after 2.4872 seconds
Stage 001 done after 2.1198 seconds
Stage 002 done after 3.0530 seconds
Stage 003 done after 14.8807 seconds
Orientation:   0%|                                                                                           | 0/1 [00:22<?, ?it/sNaN loss value, stopping!███████████████████████████████████████████████████████████▏                 | 4/5 [00:22<00:07,  7.47s/it]
Stage 004 done after 25.5808 seconds
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:48<00:00,  9.63s/it]
Body fitting Orientation 0 done after 48.1341 seconds
Body final loss val = 2266.42139
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:48<00:00, 48.14s/it]
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00001357.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
NaN loss value, stopping!
Camera initialization done after 2.5745
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "/nfs/dawnlightdb/mona/code/smplify-x-dawnlight/smplifyx/fit_single_frame.py", line 367, in fit_single_frame
    cam_init_loss_val))
TypeError: unsupported format string passed to NoneType.__format__

```

**Comment by monacv** [comment]
also now I got it for this test image from HICO dataset:

It was able to process 933 images in the test set:
```
mona@ubuntu:~/mona/data/smplify-x/djrn_test_results/meshes$ numdir
933
```

```
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00001356.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
Camera initialization done after 1.6837
Camera initialization final loss 4819.7524
Stage 000 done after 2.4872 seconds
Stage 001 done after 2.1198 seconds
Stage 002 done after 3.0530 seconds
Stage 003 done after 14.8807 seconds
Orientation:   0%|                                                                                           | 0/1 [00:22<?, ?it/sNaN loss value, stopping!███████████████████████████████████████████████████████████▏                 | 4/5 [00:22<00:07,  7.47s/it]
Stage 004 done after 25.5808 seconds
Stage: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:48<00:00,  9.63s/it]
Body fitting Orientation 0 done after 48.1341 seconds
Body final loss val = 2266.42139
Orientation: 100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:48<00:00, 48.14s/it]
Processing: ../../data/smplify-x/djrn_test_data/images/HICO_test2015_00001357.jpg
Found Trained Model: ../../data/smplify-x/vposer_v1_0/snapshots/TR00_E096.pt
NaN loss value, stopping!
Camera initialization done after 2.5745
Traceback (most recent call last):
  File "smplifyx/main.py", line 272, in <module>
    main(**args)
  File "smplifyx/main.py", line 262, in main
    **args)
  File "~/mona/code/smplify-x/smplifyx/fit_single_frame.py", line 367, in fit_single_frame
    cam_init_loss_val))
TypeError: unsupported format string passed to NoneType.__format__

```

**Comment by Foruck** [comment]
This is related to the optimizer used by SMPLify-X. The error usually occurs when the reconstruction is failed, according to our experience. We simply omit the images that cause these errors.

**Comment by monacv** [comment]
So, I was very curious and decided to run the SMPLify-X only for one of the images that we got a NAN loss for and I was able to produce meshes using SMPLify-X.

So I am very confused why do I get a NAN error when it is in a folder along with other images

![Screenshot from 2021-01-13 21-22-30](https://user-images.githubusercontent.com/76495162/104536287-d4250600-55e5-11eb-9da5-acd7b7dd32df.png)
![Screenshot from 2021-01-13 21-21-38](https://user-images.githubusercontent.com/76495162/104536303-dab37d80-55e5-11eb-8efa-251c7bbac627.png)
![Screenshot from 2021-01-13 21-21-25](https://user-images.githubusercontent.com/76495162/104536321-dedf9b00-55e5-11eb-99f1-e706106dc187.png)
![Screenshot from 2021-01-13 21-21-08](https://user-images.githubusercontent.com/76495162/104536328-e1da8b80-55e5-11eb-93a0-42e863a457cb.png)
![Screenshot from 2021-01-13 21-25-55](https://user-images.githubusercontent.com/76495162/104536344-eef77a80-55e5-11eb-95da-62ed5e39a35c.png)


Also, you mentioned that you skipped the images that had caused you problems. Could you either please share the code that does this or share the final set of train and test images that doesn't have these problems so I could reproduce your results?

Thanks a lot

**Comment by Foruck** [comment]
This is because of the LBGFS optimizer used by smplify-x. When it encounters a failure with NaN loss, the following reconstructions will also result in NaN loss even though it could have be successfully reconstructed. We will update the list of images that we successfully reconstructed.

**Comment by monacv** [comment]
@Foruck @DirtyHarryLYL you have closed this issue but the list of images for which SMPLIFY-X doesn't throw NaN loss error has not been released. Could you please provide the list of the images that were used so that I could reproduce your results? Thanks a lot.
