### ISSUE TITLE
  File "/scratch3/research/code/DJ-RN/pointnet/models/pointnet_hico.py", line 13, in placeholder_inputs     pointclouds_pl = tf.placeholder(tf.float32, AttributeError: module 'tensorflow' has no attribute 'placeholder'

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#52]
```
(djrn) [jalal@goku pointnet]$ pwd
/scratch3/research/code/DJ-RN/pointnet
```

```
(djrn) [jalal@goku pointnet]$ python Feature_extraction.py --input_list script/vertex_path_GT.txt --model_path ../Feature_extraction/model_10000.ckpt
WARNING:tensorflow:From /scratch3/venv/djrn/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "Feature_extraction.py", line 85, in <module>
    evaluate()
  File "Feature_extraction.py", line 42, in evaluate
    pointclouds_pl = MODEL.placeholder_inputs(BATCH_SIZE, NUM_POINT)
  File "/scratch3/research/code/DJ-RN/pointnet/models/pointnet_hico.py", line 13, in placeholder_inputs
    pointclouds_pl = tf.placeholder(tf.float32,
AttributeError: module 'tensorflow' has no attribute 'placeholder'


```

**Comment by monacv** [comment]
replaced all
`import tensorflow as tf`

with
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
in `pointnet`
