### ISSUE TITLE
File "script/assign_pose_Neg.py", line 26, in <module>     data = pickle.load(open('Data/Trainval_Neg_HICO_with_pose.pkl', 'rb'), encoding='latin1') FileNotFoundError: [Errno 2] No such file or directory: 'Data/Trainval_Neg_HICO_with_pose.pkl'

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#55]
I am following second part of step 5 and I get the following error:
![Screenshot from 2021-05-26 17-43-57](https://user-images.githubusercontent.com/76495162/119735227-02470c00-be4a-11eb-8016-92ecdfbb85f5.png)

```
(djrn) [jalal@goku DJ-RN]$ python script/assign_pose_Neg.py --pose ../../data/smplify-x/ride_bike/toy_dataset/tmp_data_train/keypoints/ --res ../../data/smplify-x/ride_bike/toy_dataset/tmp_res_train/results/
Traceback (most recent call last):
  File "script/assign_pose_Neg.py", line 26, in <module>
    data = pickle.load(open('Data/Trainval_Neg_HICO_with_pose.pkl', 'rb'), encoding='latin1')
FileNotFoundError: [Errno 2] No such file or directory: 'Data/Trainval_Neg_HICO_with_pose.pkl'
(djrn) [jalal@goku DJ-RN]$ pwd
/scratch3/research/code/DJ-RN
```

When I use ripgrep, it doesn't seem elsewhere in the code the file `Trainval_Neg_HICO_with_pose.pkl` is created. So, could you please share how this file is created? hmmm
```

(djrn) [jalal@goku DJ-RN]$ rg Trainval_Neg_HICO_with_pose.pkl
script/assign_pose_Neg.py
26:data = pickle.load(open('Data/Trainval_Neg_HICO_with_pose.pkl', 'rb'), encoding='latin1')
```

**Comment by monacv** [comment]
The method is written in another github repo:
`$ python script/Download_data.py 1qioujFz-jWBXPb-gCRqh6ttpf79H06Re Data/Trainval_Neg_HICO_with_pose.pkl`
https://github.com/DirtyHarryLYL/Transferable-Interactiveness-Network/blob/master/script/download_dataset.sh
