### ISSUE TITLE
hico_obj_parameter.txt is missing

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#56]
Could you please share the `hico_obj_parameter.txt` file?
```
(djrn) [jalal@goku DJ-RN]$ python script/generate_3D_obj_GT.py --smplx_path ../../data/smplify-x/models_smplx_v1_1/models/smplx/ --res ../../data/smplify-x/ride_bike/toy_dataset/tmp_res_train/results/ --img_path ../../data/smplify-x/ride_bike/toy_dataset/tmp_data_train/images/ --save_obj_path ../../data/smplify-x/ride_bike/toy_dataset/object_mesh/
Traceback (most recent call last):
  File "script/generate_3D_obj_GT.py", line 38, in <module>
    list_hoi, order_obj_list, obj_para_dict = get_order_obj()
  File "/scratch3/research/code/DJ-RN/script/generate_utils.py", line 52, in get_order_obj
    f = open('hico_obj_parameter.txt','r')
FileNotFoundError: [Errno 2] No such file or directory: 'hico_obj_parameter.txt'
```

**Comment by monacv** [comment]
file was in script folder and moved it to DJ-RN root

```
(djrn) [jalal@goku DJ-RN]$ find . -name "hico_obj_parameter.txt"
./script/hico_obj_parameter.txt

```
