### ISSUE TITLE
 File "script/concat_w2v.py", line 80, in <module>     hoi_class = Trainval_Neg[key][i][1][0] TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by monacv** [DirtyHarryLYL/DJ-RN#66]
```
(djrn) [jalal@goku DJ-RN-dawnlight]$ python script/concat_w2v.py --SMPLX_PATH /scratch3/research/data/smplify-x/ride_bike/combined_smplx_results --GT Data/Trainval_GT_HICO_with_idx.pkl --Neg Data/Trainval_Neg_HICO_with_idx.pkl --Test Data/Test_Faster_RCNN_R-50-PFN_2x_HICO_DET_with_idx.pkl
Traceback (most recent call last):
  File "script/concat_w2v.py", line 80, in <module>
    hoi_class = Trainval_Neg[key][i][1][0]
TypeError: 'int' object is not subscriptable

```

**Comment by monacv** [comment]
So, we have these:

`hoi_class = Trainval_Neg[key][i][1][0]`

and
`(Pdb) Trainval_Neg[key][i]`
is:

`[2, 53, array([257.58002 ,   2.112835, 631.65155 , 128.04715 ], dtype=float32), array([129.54727 ,  65.349594, 180.34726 , 148.78911 ], dtype=float32), [46, 47, 48, 49, 50, 51, 52, 53], 40, array(0.7580195, dtype=float32), [509.0626220703125, 102.97746276855469, 0.0063692303374409676, 432.80535888671875, 20.08914566040039, 0.00269611575640738, 442.751953125, 83.08427429199219, 0.01013473141938448, 439.4364318847656, 33.35127639770508, 0.0054231444373726845, 598.5820922851562, 63.19107437133789, 0.006247746292501688, 469.2762451171875, 10.142535209655762, 0.009487876668572426, 296.86846923828125, 36.66679763793945, 0.10179778933525085, 601.8975830078125, 6.826998710632324, 0.6581866145133972, 286.921875, 43.29788589477539, 0.01269484031945467, 449.383056640625, 53.24446487426758, 0.7015854120254517, 446.0675048828125, 76.45320129394531, 0.04809676483273506, 548.8490600585938, 26.720203399658203, 0.09591742604970932, 462.6451721191406, 83.08427429199219, 0.03613485395908356, 601.8975830078125, 66.50660705566406, 0.5811274647712708, 472.5917663574219, 89.71534729003906, 0.14602448046207428, 432.80535888671875, 56.56001663208008, 0.019369112327694893, 472.5917663574219, 83.08427429199219, 0.06064879521727562], -1]`


`for key = 2 and i = 0`

and

```
(Pdb) Trainval_Neg[key][i][1]
53
```

as you see number 53 is not subscriptable 

```
(Pdb) Trainval_Neg[key][i][1][0]
*** TypeError: 'int' object is not subscriptable
```


So could you please share what you had in mind and what's a fix for this? Since the code has no documentation, I am not able to understand what you intended to do. 


```
for key in Trainval_Neg:
    for i in range(len(Trainval_Neg[key])):
        pdb.set_trace()
        try:
            hoi_class = Trainval_Neg[key][i][1][0]
            print("I am here", i)
            cur_obj   = mapping[hoi_class]
            obj_holder = np.tile(obj_vec[cur_obj], (312, 1))
            holder = np.concatenate([part_holder, obj_holder], axis=0)
            if os.path.exists(args.SMPLX_PATH + '/results/HICO_train2015_%08d/%03d.pkl' % (key, Trainval_Neg[key][i][-1])):
                pc = pickle.load(open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'rb'))
                pc = np.concatenate([pc, holder], axis=1)
                pickle.dump(pc, open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'wb'))
        except TypeError as e:
            print(e)
            print(i)
            continue
```

**Comment by Foruck** [comment]
Delete the subscription of `[0]` should help. We have fixed it in the latest commit.

**Comment by monajalal** [comment]
@Foruck  Thanks a lot for your response :) 
so after that change, the script gets stuck in dump:

I have been printing the index of that i and is 6:

```
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 10
I am here 11
I am here 12
I am here 13
I am here 14
I am here 15
I am here 16
I am here 17
I am here 18
I am here 19
I am here 20
I am here 21
I am here 22
I am here 23
I am here 24
I am here 25
I am here 26
I am here 27
I am here 28
I am here 29
I am here 0
I am here 1
I am here 2
I am here 3
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 10
I am here 11
I am here 12
I am here 13
I am here 14
I am here 15
I am here 16
I am here 17
I am here 18
I am here 19
I am here 20
I am here 21
I am here 22
I am here 23
I am here 24
I am here 25
I am here 26
I am here 27
I am here 28
I am here 29
I am here 30
I am here 31
I am here 32
I am here 33
I am here 34
I am here 0
I am here 1
I am here 2
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 10
I am here 11
I am here 0
I am here 1
I am here 2
I am here 3
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 0
I am here 1
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 0
I am here 1
I am here 2
I am here 3
I am here 0
I am here 1
I am here 2
I am here 0
I am here 0
I am here 1
I am here 0
I am here 1
I am here 2
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6
I am here 7
I am here 8
I am here 9
I am here 0
I am here 0
I am here 1
I am here 0
I am here 1
I am here 2
I am here 3
I am here 0
I am here 1
I am here 0
I am here 1
I am here 0
I am here 1
I am here 2
I am here 0
I am here 1
I am here 0
I am here 1
I am here 2
I am here 3
I am here 4
I am here 5
I am here 6

```

I was not sure how to debug it. Do you know why it gets stuck in dumping and how I could fix it?

```
for key in Trainval_Neg:
    for i in range(len(Trainval_Neg[key])): 
        #pdb.set_trace()
        try:
            hoi_class = Trainval_Neg[key][i][1]#[0]
            print("I am here", i)
            cur_obj   = mapping[hoi_class]
            obj_holder = np.tile(obj_vec[int(cur_obj)], (312, 1))
            holder = np.concatenate([part_holder, obj_holder], axis=0)
            if os.path.exists(args.SMPLX_PATH + '/results/HICO_train2015_%08d/%03d.pkl' % (key, Trainval_Neg[key][i][-1])):
                pc = pickle.load(open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'rb'))
                pc = np.concatenate([pc, holder], axis=1)
                print('pc shape: ', pc.shape)
                pickle.dump(pc, open(args.SMPLX_PATH + '/object_NEG/HICO_train2015_%08d/%03d_feature.pkl' % (key, i), 'wb'))
        except TypeError as e:
            print(e)
            print(i)
            continue
        except Exception as e:
            print(e)
            print(i)
```

**Comment by monacv** [comment]
Thanks a lot for your response :) @Foruck
