### ISSUE TITLE
errors in bash script

### ISSUE THREAD

**Issue by monajalal** [DirtyHarryLYL/DJ-RN#9]
```
[128][mona.goku: DJ-RN]$ bash script/Generate_Ambiguous_HOI.sh
script/Generate_Ambiguous_HOI.sh: line 2: $'\r': command not found
script/Generate_Ambiguous_HOI.sh: line 3: cd: $'Data\r': No such file or directory
script/Generate_Ambiguous_HOI.sh: line 4: $'\r': command not found
script/Download_data.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:
^CTraceback (most recent call last):
  File "script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "script/Download_data.py", line 27, in save_response_content
    f.write(chunk)
KeyboardInterrupt

```

**Comment by Foruck** [comment]
Thanks for using. Would you mind provide more detailed information on the environment you used?

**Comment by monacv** [comment]
@Foruck 
```
15856/31773MB
[18986:2271 0:440] 07:15:52 Wed Dec 23 [mona@goku:pts/3 +1] ~/research/code
$ git clone https://github.com/DirtyHarryLYL/DJ-RN.git
Cloning into 'DJ-RN'...
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (90/90), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 199 (delta 50), reused 0 (delta 0), pack-reused 109
Receiving objects: 100% (199/199), 5.25 MiB | 7.57 MiB/s, done.
Resolving deltas: 100% (83/83), done.
16100/31773MB
[18986:2271 0:441] 07:16:07 Wed Dec 23 [mona@goku:pts/3 +1] ~/research/code
$ cd DJ-RN/
16185/31773MB
[18986:2271 0:442] 07:16:11 Wed Dec 23 [mona@goku:pts/3 +1] ~/research/code/DJ-RN
$ bash script/Generate_Ambiguous_HOI.sh
script/Generate_Ambiguous_HOI.sh: line 2: $'\r': command not found
script/Generate_Ambiguous_HOI.sh: line 3: cd: $'Data\r': No such file or directory
script/Generate_Ambiguous_HOI.sh: line 4: $'\r': command not found
script/Download_data.py:45: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(sys.argv) is not 3:

^CTraceback (most recent call last):
  File "script/Download_data.py", line 52, in <module>
    download_file_from_google_drive(file_id, destination)
  File "script/Download_data.py", line 40, in download_file_from_google_drive
    save_response_content(response, destination)
  File "script/Download_data.py", line 25, in save_response_content
    for chunk in response.iter_content(CHUNK_SIZE):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 571, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 766, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/home/mona/anaconda3/lib/python3.8/site-packages/urllib3/response.py", line 719, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/home/mona/anaconda3/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/home/mona/anaconda3/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/mona/anaconda3/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

16324/31773MB
[18986:2271 0:443] 07:16:25 Wed Dec 23 [mona@goku:pts/3 +1] ~/research/code/DJ-RN
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
16324/31773MB
[18986:2271 0:444] 07:16:34 Wed Dec 23 [mona@goku:pts/3 +1] ~/research/code/DJ-RN
$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by monacv** [comment]
```
$ dos2unix  script/Generate_Ambiguous_HOI.sh 
dos2unix: converting file script/Generate_Ambiguous_HOI.sh to Unix format...

```

fixed the issue.

**Comment by monacv** [comment]
also, relative addresses in the bash script are wrong

examples:
```

python: can't open file 'script/Download_data.py': [Errno 2] No such file or directory

tar: Ambiguous_HOI.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```
